language: c
sudo: required

env:
  global:
     - PRETTYNAME="DLog"
     - APPLICATION_FOLDER="${HOME}/arduino-ide"
     - SKETCHBOOK_FOLDER="${HOME}/arduino-sketchbook"

before_install:
  - git clone https://github.com/per1234/arduino-ci-script.git "${HOME}/scripts"
  - cd "${HOME}/scripts"
  # Get new tags from the remote
  - git fetch --tags
  # Checkout the latest tag
  - git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
  - source "${HOME}/scripts/arduino-ci-script.sh"

  # Uncomment the following lines to get verbose output for debugging
  # 0 (minimum/default) - 2 (maximum) verbosity
  - set_script_verbosity 1
  # Turn on verbose output during compilation
  #- set_verbose_output_during_compilation "true"

  # Check for library issues that don't affect compilation
  - set_library_testing "true"

  - set_application_folder "$APPLICATION_FOLDER"
  - set_sketchbook_folder "$SKETCHBOOK_FOLDER"

  - install_ide "1.8.5"

  - install_package "arduino:avr"
  - install_package esp8266:esp8266 "http://arduino.esp8266.com/stable/package_esp8266com_index.json"

#  - sudo dpkg --add-architecture i386
#  - sudo apt-get update
#  - sudo apt-get -y install libc6:i386 libstdc++6:i386 libncurses5:i386 libudev1:i386

  # install esp32
  #- pushd .
  #- mkdir -p ~/Arduino/hardware/espressif
  #- cd ~/Arduino/hardware/espressif
  #- git clone https://github.com/espressif/arduino-esp32.git esp32
  #- cd esp32
  #- git submodule update --init --recursive
  #- cd tools
  #- python2 get.py
  #- popd

  # install the library from repo
  - install_library
  - echo "install done"

script:
  - echo "starting tests"
  - build_sketch "${SKETCHBOOK_FOLDER}/libraries/MouseTo/examples" "esp8266:esp8266:generic:CpuFrequency=80,CrystalFreq=26,FlashFreq=40,FlashMode=qio,FlashSize=4M1M,led=2,LwIPVariant=v2mss536,Debug=Serial,DebugLevel=CORE" "false" "1.8.5"
